table Ventas
	lineageTag: 98de2de6-8d68-44e7-a686-d56396975d7d

	measure 'Venta USD' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        SUMX(
			            'Ventas',
			            'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]
			        ),
			        'Ventas'[Fecha] <= Limite,
			        YEAR('Ventas'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: 85aa3c60-2157-48b5-a303-3be2ff654b15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Costo USD' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        SUMX(
			            'Ventas',
			            'Ventas'[Cantidad] * RELATED('Productos'[Costo])
			        ),
			        'Ventas'[Fecha] <= Limite,
			        YEAR('Ventas'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: 09c869d8-6161-40b5-9442-200ddc7ba3c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Margen USD' = [Venta USD] - [Costo USD]
		lineageTag: 86972f40-c552-41e3-a646-8d66ed918d62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cantidad_Metrica = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        SUM('Ventas'[Cantidad]),
			        'Ventas'[Fecha] <= Limite,
			        YEAR('Ventas'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: ce0c2eaa-6f7e-4157-8175-bf2f1d8adca4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Kilogramos =
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        SUMX(
			            'Ventas',
			            'Ventas'[Cantidad] * RELATED('Productos'[Peso_KG])
			        ),
			        'Ventas'[Fecha] <= Limite,
			        YEAR('Ventas'[Fecha]) = AnioActual
			    )
		lineageTag: 9e1090e9-3c24-4141-8d3c-f3f84c865fef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ticket Promedio' =
			
			DIVIDE([Venta USD], DISTINCTCOUNT('Ventas'[OrderKey]))
		lineageTag: cdef84a4-fad9-448e-8eff-44e6a05f7a09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Precio Promedio USD' = DIVIDE([Venta USD], [Cantidad_Metrica])
		lineageTag: 44151174-0258-45ff-b08a-d28c8d2d83f6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Precio Promedio por Kilogramo' =
			
			DIVIDE([Venta USD], [Kilogramos])
		lineageTag: 4e14e518-7647-401d-9342-0a5e2b4cb94d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta Promedio por Cliente' =
			
			DIVIDE([Venta USD], DISTINCTCOUNT('Ventas'[CustomerKey]))
		lineageTag: e26a857c-f027-4f86-b84e-4856a69c8ec2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unidades Promedio por Ticket' =
			
			DIVIDE([Cantidad_Metrica], DISTINCTCOUNT('Ventas'[OrderKey]))
		lineageTag: 997c5de4-7487-4c06-b019-217aff77f110

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta USD AA' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR LimiteAA = EDATE(Limite, -12)
			VAR AnioAnterior = YEAR(Limite) - 1
			RETURN
			    CALCULATE(
			        SUMX(
			            'Ventas',
			            'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]
			        ),
			        'Ventas'[Fecha] <= LimiteAA,
			        YEAR('Ventas'[Fecha]) = AnioAnterior
			    )
			
			```
		lineageTag: 93b975d8-4e7d-4205-94ec-5e9f9a987504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Venta USD' = ```
			[Venta USD] - [Venta USD AA]
			
			```
		lineageTag: ba05fa6d-761a-451e-a997-e9374d5bceb0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Venta USD' = ```
			
			DIVIDE([Var Venta USD], [Venta USD AA])
			
			```
		lineageTag: 8e5a4884-8fb3-4cc4-bfe2-282981d13973

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta USD MTD' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        TOTALMTD(
			            SUMX('Ventas', 'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]),
			            'Calendario'[Fecha]
			        ),
			        'Calendario'[Fecha] <= Limite,
			        YEAR('Calendario'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: 32281153-4882-4c83-8a73-5432a68bfa56

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta USD MTD AA' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR LimiteAA = EDATE(Limite, -12)
			VAR AnioAnterior = YEAR(Limite) - 1
			RETURN
			    CALCULATE(
			        TOTALMTD(
			            SUMX('Ventas', 'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]),
			            'Calendario'[Fecha]
			        ),
			        'Calendario'[Fecha] <= LimiteAA,
			        YEAR('Calendario'[Fecha]) = AnioAnterior
			    )
			
			```
		lineageTag: 644fbaf2-4ac5-4aae-aa39-036adf6512b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Venta USD MTD' = ```
			[Venta USD MTD] - [Venta USD MTD AA]
			
			```
		lineageTag: 297bfa87-eac0-44bc-8af4-c12d0053d9fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Venta USD MTD' = ```
			
			DIVIDE([Var Venta USD MTD], [Venta USD MTD AA])
			
			```
		lineageTag: 4540b274-5c47-4678-9af1-780dd922128b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta USD YTD' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        TOTALYTD(
			            SUMX('Ventas', 'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]),
			            'Calendario'[Fecha]
			        ),
			        'Calendario'[Fecha] <= Limite,
			        YEAR('Calendario'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: 5fdaa941-7e7b-423e-b7ec-cea9ad1c2e39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Venta USD YTD AA' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR LimiteAA = EDATE(Limite, -12)
			VAR AnioAnterior = YEAR(Limite) - 1
			RETURN
			    CALCULATE(
			        TOTALYTD(
			            SUMX('Ventas', 'Ventas'[Cantidad] * 'Ventas'[PrecioNeto_USD]),
			            'Calendario'[Fecha]
			        ),
			        'Calendario'[Fecha] <= LimiteAA,
			        YEAR('Calendario'[Fecha]) = AnioAnterior
			    )
			
			```
		lineageTag: 19609e06-24e8-4aa5-9851-b41bb71a5098

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Venta USD YTD' = ```
			[Venta USD YTD] - [Venta USD YTD AA]
			
			```
		lineageTag: 7992e70c-0ef7-439c-8226-8e417ef5fc84

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Delta Venta USD YTD' = ```
			
			DIVIDE([Var Venta USD YTD], [Venta USD YTD AA])
			
			```
		lineageTag: 45a22586-a2f5-4dd4-bcaa-4a994f44d8b5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Descuento USD' = ```
			
			VAR Limite = CALCULATE(MAX('Ventas'[Fecha]))
			VAR AnioActual = YEAR(Limite)
			RETURN
			    CALCULATE(
			        SUMX(
			            'Ventas',
			            'Ventas'[Cantidad] * ('Ventas'[PrecioUnitario_USD] - 'Ventas'[PrecioNeto_USD])
			        ),
			        'Ventas'[Fecha] <= Limite,
			        YEAR('Ventas'[Fecha]) = AnioActual
			    )
			
			```
		lineageTag: d248c0ea-f17d-4350-bd8d-48505c2c9630

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DescuentoSobreVenta = DIVIDE([Descuento USD], [Venta USD])
		lineageTag: ef520c76-f023-4407-8942-8ced77ca5ec8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderKey
		dataType: int64
		formatString: 0
		lineageTag: c8229e8f-b769-41a9-b43f-ed2606af3bc0
		summarizeBy: count
		sourceColumn: OrderKey

		annotation SummarizationSetBy = Automatic

	column NumeroLinea
		dataType: int64
		formatString: 0
		lineageTag: 578152a1-d6be-4754-ba81-4a6a71acb498
		summarizeBy: sum
		sourceColumn: NumeroLinea

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 01f6207c-1033-400a-b377-1dee4d1bc2be
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		formatString: 0
		lineageTag: cd039cd0-5a29-40dc-b961-57a43aece31e
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 888db323-bed2-48b8-b148-341cf030bb22
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: General Date
		lineageTag: e2b2c535-94c2-4d0f-80ec-5b3f1b3ebbdb
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column MonedaOriginal
		dataType: string
		lineageTag: e1ea4dfa-e816-49c5-acdb-6ca9ed67b9df
		summarizeBy: none
		sourceColumn: MonedaOriginal

		annotation SummarizationSetBy = Automatic

	column Cantidad
		dataType: double
		lineageTag: dade1a06-3d6a-4393-9c80-726d740fc390
		summarizeBy: sum
		sourceColumn: Cantidad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrecioUnitario_USD
		dataType: double
		lineageTag: 3bd10f21-e3ff-43a8-8731-00fb3f8dd666
		summarizeBy: sum
		sourceColumn: PrecioUnitario_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrecioNeto_USD
		dataType: double
		lineageTag: 6060b2a1-c20d-42a6-8f21-e01c44254aac
		summarizeBy: sum
		sourceColumn: PrecioNeto_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostoUnitario_USD
		dataType: double
		lineageTag: 42707dcd-f0c6-4a92-b579-bb44b5fe637d
		summarizeBy: sum
		sourceColumn: CostoUnitario_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Ventas = m
		mode: import
		source =
				let
				    Origen = Sql.Database("tdw-assesment.cwb0siyssle1.us-east-1.rds.amazonaws.com", "assesment", [Query="SELECT #(lf)    sd.OrderKey,#(lf)    sd.LineNumber AS NumeroLinea,#(lf)    sh.CustomerKey,#(lf)    sh.StoreKey,#(lf)    sd.ProductKey,#(lf)    sh.OrderDate AS Fecha,#(lf)    sh.CurrencyCode AS MonedaOriginal,#(lf)    sd.Quantity AS Cantidad,#(lf)    sd.UnitPrice * ce.Exchange AS PrecioUnitario_USD,#(lf)    sd.NetPrice * ce.Exchange AS PrecioNeto_USD,#(lf)    sd.UnitCost * ce.Exchange AS CostoUnitario_USD#(lf)FROM Data.Sales_Details AS sd#(lf)JOIN Data.Sales_Header AS sh ON sd.OrderKey = sh.OrderKey#(lf)LEFT JOIN Data.CurrencyExchange AS ce#(lf)    ON ce.FromCurrency = sh.CurrencyCode#(lf)    AND ce.ToCurrency = 'USD'#(lf)    AND ce.Date = sh.OrderDate#(lf)WHERE sh.CurrencyCode IN ('CAD', 'USD', 'GBP', 'AUD', 'EUR');"])
				in
				    Origen

	changedProperty = Name

	annotation PBI_ResultType = Table

